version: "3.9"

services:
  web:
    build:
      context: "gym-one-fr"
    image: "frontend-app"
    container_name: "frontend-app-container"
    ports:
      - "${WEB_PORT}:80"
  api:
    build:
      context: "GymOneBackend/GymOneBackend.WebAPI"
    image: "backend-api"
    container_name: "backend-api-container"
    ports:
      - "${API_PORT}:80"
