version: "3.9"

services:
  web:
    build:
      context: "gym-one-fr"
    image: "frontend-app"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
  api:
    build:
      context: "GymOneBackend/GymOneBackend.WebAPI"
    image: "backend-api"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
