version: "3.9"

services:
  web:
    image: "frontend-app"
    build:
      context: "gym-one-fr"
    container_name: "frontend-app-container"
    ports:
      - "8090:80"
  api:
    image: "backend-api"
    build:
    context: "API"
    container_name: "backend-api-container"
    ports:
      - "8091:80"
